language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - python manage.py test --settings=bucketlist.settings_template
  - coverage run manage.py test --settings=bucketlist.settings_template
after_success:
  - bash <(curl -s https://codecov.io/bash)
