# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160517_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dream'),
            preserve_default=False,
        ),
    ]
