# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160523_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private'), ('SHARED', 'shared')], max_length=8),
        ),
    ]
