# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160524_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('CRD', 'created'), ('PLD', 'planned'), ('PROG', 'processing'), ('POST', 'postponed'), ('ACD', 'achieved'), ('DRD', 'dropped')], default='CRD', max_length=4),
        ),
        migrations.AlterField(
            model_name='dream',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'public'), ('PRI', 'private'), ('SHD', 'shared')], default='PUB', max_length=3),
        ),
    ]
